#!/usr/bin/env python3
"""Emit the RTL geometry table from bench/units.py.

docs/MEASUREMENT.md notes that the RTL does not share the units table. This closes
that: the same file that defines the correctness gate's geometry defines the
hardware's, so a variant is one --variant flag away from being synthesised rather
than a rewrite of is_valid().

  gen_geom.py --variant diagonal > sud_geom.svh
"""
import sys, os, argparse
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "bench"))
import units as UNITS

ap = argparse.ArgumentParser()
ap.add_argument("--variant", default="classic")
a = ap.parse_args()

us = UNITS.units(a.variant)
NU = len(us)
NC = 81
uof = [[] for _ in range(NC)]
for k, u in enumerate(us):
    for c in u:
        uof[c].append(k)
MAXUOF = max(len(x) for x in uof)

o = sys.stdout.write
o("// GENERATED by explore/model/gen_geom.py --variant %s -- do not edit.\n" % a.variant)
o("// Geometry comes from bench/units.py, the same table the correctness gate uses.\n")
o("// variant=%s  units=%d  units-per-cell max=%d\n" % (a.variant, NU, MAXUOF))
o("localparam int SUD_NC   = %d;\n" % NC)
o("localparam int SUD_NU   = %d;\n" % NU)
o("localparam int SUD_UPC  = %d;   // max units any one cell belongs to\n" % MAXUOF)

# MEMBER[u] = 81-bit mask of the cells in unit u
o("\n// MEMBER[u][c] = 1 when cell c is in unit u\n")
o("localparam bit [SUD_NU-1:0][SUD_NC-1:0] SUD_MEMBER = '{\n")
rows = []
for k in range(NU - 1, -1, -1):          # packed array: index NU-1 first
    m = 0
    for c in us[k]:
        m |= 1 << c
    rows.append("    81'h%021x" % m)
o(",\n".join(rows))
o("\n};\n")

# UNIT_CELLS[u][k] = the cell index at position k of unit u (ordered)
o("\n// UNIT_CELLS[u][k] = cell index at slot k of unit u (slot order is fixed and\n"
  "// is what the hidden-single priority is defined against)\n")
o("localparam bit [SUD_NU-1:0][8:0][6:0] SUD_UNIT_CELLS = '{\n")
rows = []
for k in range(NU - 1, -1, -1):
    cells = ", ".join("7'd%d" % c for c in reversed(us[k]))
    rows.append("    '{%s}" % cells)
o(",\n".join(rows))
o("\n};\n")
